spring.datasource.url=${DB_HOST:jdbc:h2:mem:test}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:sa}
logging.level.web=DEBUG
spring.jpa.hibernate.ddl-auto=${USERMANAGER_DDL:create}
spring.jpa.show-sql=true
api.version=v1
info.app.name=User Manager
info.app.java.version=${java.version}
